version: '3.7'
services:
  srv-della_parser:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: srv-della_parser
#    external_links:
#        - main_database_1
    ports:
      - "5000:5000"

    command: python ./app.py
